remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navigation:
  - title: "Sketches"
    url: "#Sketches"
  - title: "Introduction"
    url: "#Introduction"
  - title: "Solution"
    url: "#Solution"
  - title: "Research"
    url: "#Research"
  - title: "Personas"
    url: "#Personas"


